In [2]:
import torch

a = torch.tensor([1, 2, 3, 4, 5])
print(a, type(a))

b = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float64)
print(b, type(b))

tensor([1, 2, 3, 4, 5]) <class 'torch.Tensor'>
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64) <class 'torch.Tensor'>


In [22]:
d = torch.arange(0, 10, 2)
print(d)

e = torch.zeros(3, 3)
print(e)

f = torch.rand(2, 3)
print(f)
print(f.size())

tensor([0, 2, 4, 6, 8])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.8630, 0.8551, 0.6843],
        [0.4447, 0.5660, 0.8132]])
torch.Size([2, 3])


In [23]:
g = torch.linspace(-5, 5, 10)
print(g)

tensor([-5.0000, -3.8889, -2.7778, -1.6667, -0.5556,  0.5556,  1.6667,  2.7778,
         3.8889,  5.0000])


In [26]:
a = torch.tensor([[1, 2], [3, 4]])

b = a.numpy()
print(b, type(b))

c = torch.from_numpy(b)
print(c, type(c))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [31]:
#torch.view() is used to reshape the tensor
a = torch.arange(0, 12)
print(a)
b = a.view(3, 4)
print(b)
c = a.view(2, -1)
print(c)
# 1次元に変換
f = a.view(-1)
print(f)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [36]:
g = torch.arange(0, 8).view(1, 2, 1, 4)
print(g)

h = g.squeeze()
print(h)

i = torch.arange(0, 8).view(2, -1)
print(i)

j = i.unsqueeze(2)
print(j)

tensor([[[[0, 1, 2, 3]],

         [[4, 5, 6, 7]]]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[[0],
         [1],
         [2],
         [3]],

        [[4],
         [5],
         [6],
         [7]]])
