In [6]:
import torch

x = torch.ones([2, 3], requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [7]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3., 3.],
        [3., 3., 3.]], grad_fn=<AddBackward0>)


In [8]:
z = y * 3
out = z.mean()
print(z, out)

tensor([[9., 9., 9.],
        [9., 9., 9.]], grad_fn=<MulBackward0>) tensor(9., grad_fn=<MeanBackward0>)


## 傾きの表示

In [12]:
a = torch.tensor([1.0], requires_grad=True)
b = a * 2
# 逆伝播
b.backward()
# aの勾配を表示（aの変化に対するbの変化の割合）
print(a.grad)

tensor([2.])
